<div align="center">

## UNIVERSIDAD DE LAS FUERZAS ARMADAS - ESPE

<img src="https://upload.wikimedia.org/wikipedia/commons/2/27/Logo_ESPE.png" alt="logo_espe" width="200">

<hr>

### INGENIERÍA EN TI 
### ESTUDIANTE: NICOLÁS MUÑOZ
### NRC: 3977
### DOCENTE: ING. ADRIAN CEDEÑO
### Actividad 1

#### Fecha : 11/20/24

<hr>

</div>


## Operaciones con matrices y vectores

### 1. Vectores u y v:

$\mathbf{u} = \begin{bmatrix} 0 & 9 & 1 & 8 \end{bmatrix}$

$\mathbf{v} = \begin{bmatrix} 9 & 8 & 6 & 2 \end{bmatrix}$

### 2. Suma de vectores u + v:

$\mathbf{u} + \mathbf{v} = \begin{bmatrix} 0 & 9 & 1 & 8 \end{bmatrix} + \begin{bmatrix} 9 & 8 & 6 & 2 \end{bmatrix} = \begin{bmatrix} 0+9 & 9+8 & 1+6 & 8+2 \end{bmatrix} = \begin{bmatrix} 9 & 17 & 7 & 10 \end{bmatrix}$

### 3. Matrices A y B:

$A = \begin{bmatrix} 8 & 3 & 4 \\ 4 & 6 & 2 \\ 1 & 5 & 2 \\ 6 & 2 & 7 \end{bmatrix}$

$B = \begin{bmatrix} 2 & -1 & 1 & 3 \\ 3 & 9 & 1 & 2 \\ 5 & 1 & 4 & 6 \\ 2 & 3 & 7 & 2 \end{bmatrix}$

### 4. Resta de matrices A - B:

$A - B = \begin{bmatrix} 8 & 3 & 4 \\ 4 & 6 & 2 \\ 1 & 5 & 2 \\ 6 & 2 & 7 \end{bmatrix} - \begin{bmatrix} 2 & -1 & 1 & 3 \\ 3 & 9 & 1 & 2 \\ 5 & 1 & 4 & 6 \\ 2 & 3 & 7 & 2 \end{bmatrix} = \boxed{\text{Dimensiones incompatibles}}$ 

### 5. Producto matricial u * v (incompatible):

\begin{equation*}
\mathbf{u} \cdot \mathbf{v} = \begin{bmatrix} 0 & 9 & 1 & 8 \end{bmatrix} \cdot \begin{bmatrix} 9 & 8 & 6 & 2 \end{bmatrix} =  \boxed{\text{Dimensiones incompatibles}}
\end{equation*}

### 6. Producto matricial  u<sup>T</sup> * v :

\begin{equation*}
\mathbf{u}^T \cdot \mathbf{v} = \begin{bmatrix} 0 \\ 9 \\ 1 \\ 8 \end{bmatrix} \cdot \begin{bmatrix} 9 & 8 & 6 & 2 \end{bmatrix} = 
\begin{bmatrix} 
0\cdot9 & 0\cdot8 & 0\cdot6 & 0\cdot2 \\
9\cdot9 & 9\cdot8 & 9\cdot6 & 9\cdot2 \\
1\cdot9 & 1\cdot8 & 1\cdot6 & 1\cdot2 \\
8\cdot9 & 8\cdot8 & 8\cdot6 & 8\cdot2 
\end{bmatrix}
= \begin{bmatrix} 0 & 0 & 0 & 0 \\ 81 & 72 & 54 & 18 \\ 9 & 8 & 6 & 2 \\ 72 & 64 & 48 & 16 \end{bmatrix}
\end{equation*}

### 7.  Producto matricial A * B (incompatible):

$ A \cdot B = \begin{bmatrix} 8 & 3 & 4 \\ 4 & 6 & 2 \\ 1 & 5 & 2 \\ 6 & 2 & 7 \end{bmatrix}  \cdot \begin{bmatrix} 2 & -1 & 1 & 3 \\ 3 & 9 & 1 & 2 \\ 5 & 1 & 4 & 6 \\ 2 & 3 & 7 & 2 \end{bmatrix} = \boxed{\text{Dimensiones incompatibles}}$ 

### 8. Producto matricial B * A:

\begin{equation*}
B \cdot A =  \begin{bmatrix} 2 & -1 & 1 & 3 \\ 3 & 9 & 1 & 2 \\ 5 & 1 & 4 & 6 \\ 2 & 3 & 7 & 2 \end{bmatrix} \cdot \begin{bmatrix} 8 & 3 & 4 \\ 4 & 6 & 2 \\ 1 & 5 & 2 \\ 6 & 2 & 7 \end{bmatrix} = 
\begin{bmatrix} 
2\cdot8 + (-1)\cdot4 + 1\cdot1 + 3\cdot6 & 2\cdot3 + (-1)\cdot6 + 1\cdot5 + 3\cdot2 & 2\cdot4 + (-1)\cdot2 + 1\cdot2 + 3\cdot7 \\
3\cdot8 + 9\cdot4 + 1\cdot1 + 2\cdot6 & 3\cdot3 + 9\cdot6 + 1\cdot5 + 2\cdot2 & 3\cdot4 + 9\cdot2 + 1\cdot2 + 2\cdot7 \\
5\cdot8 + 1\cdot4 + 4\cdot1 + 6\cdot6 & 5\cdot3 + 1\cdot6 + 4\cdot5 + 6\cdot2 & 5\cdot4 + 1\cdot2 + 4\cdot2 + 6\cdot7 \\
2\cdot8 + 3\cdot4 + 7\cdot1 + 2\cdot6 & 2\cdot3 + 3\cdot6 + 7\cdot5 + 2\cdot2 & 2\cdot4 + 3\cdot2 + 7\cdot2 + 2\cdot7 
\end{bmatrix}
\end{equation*}

\begin{equation*}
= \begin{bmatrix} 31 & 11 & 29 \\ 73 & 71 & 48  \\ 84 & 53 & 72 \\ 45 & 59 & 42 \end{bmatrix}
\end{equation*}

In [1]:
# importacion de libreias 

import numpy as np 

# importante ! : ELIMINAR TODOS LOS PRINTS ()

In [2]:
#? creacion de vector u & v

#! vectorBidemensional = np.array([[2,1,4,6],[1,6,7,5]]) 
u= np.array([0,9,1,8])
u = u.reshape(1, -1) #! dejar estandar vector fila

v= np.array([9,8,6,2])
v = v.reshape(1, -1) #! dejar estandar vector fila


In [3]:
#? creacion de mi variable suma1

suma1= u+v
#? impresión de respuesta suma1
print(suma1)

#? creación de mi matriz A & B 

A= np.array([[8,3,4],[4,6,2],[1,5,2],[6,2,7]])
print(A)
B= np.array([[2,-1,1,3],[3,9,1,2],[5,1,4,6],[2,3,7,2]])
print("\n")
print(B)

[[ 9 17  7 10]]
[[8 3 4]
 [4 6 2]
 [1 5 2]
 [6 2 7]]


[[ 2 -1  1  3]
 [ 3  9  1  2]
 [ 5  1  4  6]
 [ 2  3  7  2]]


In [4]:
# ! creacion de mi variable suma2
# ! el operador subtract permite hacer la diferencia de matrices

#! suma 2 , resta de matrices 

try:
   suma2= np.subtract(A,B)
except ValueError:
   suma2="Dimensiones incompatibles"
   
print(suma2)
    

Dimensiones incompatibles


In [7]:
#? producto matricial prodmtx1
try:
   prodmtx1= np.dot(u,v)
except ValueError :
    prodmtx1="Dimensiones incompatibles"


print("El producto matricial de u y v: ",prodmtx1)


El producto matricial de u y v:  Dimensiones incompatibles


In [5]:
#? producto matricial prodmtx2
#! crear transpuesta de v

vT = v.reshape(-1, 1) #!  transformar de una vector fila a un vector columna (quito fila y dejo columna)

print(f"\nTranspuesta de <v>: {vT}")
prodmtx2=np.dot(u,vT) 
print(f"\nProducto matricial de u*vT:\n {prodmtx2}")



Transpuesta de <v>: [[9]
 [8]
 [6]
 [2]]

Producto matricial de u*vT:
 [[94]]


In [8]:
#? producto matricial prodmtx3

try:
   prodmtx3= np.dot(A,B)
except ValueError :
    prodmtx3="Dimensiones incompatibles"



In [9]:
#? producto matricial prodmtx4


prodmtx4=np.dot(B,A) 
print(f"\nProducto matricial de BA:\n {prodmtx4}")



Producto matricial de BA:
 [[31 11 29]
 [73 72 46]
 [84 53 72]
 [47 63 42]]


In [10]:
#? prodcu1= uv
prodcu1= u*v
print(f"\nproducto elemento a elemento de uv:\n {prodcu1}\n")


producto elemento a elemento de uv:
 [[ 0 72  6 16]]



In [11]:
#? prodcu2= uTV
#* transpuesta de u : 
uT = u.reshape(-1, 1) #!  transformar de una vector fila a un vector columna (quito fila y dejo columna)

print(f"\ndimension u: {np.shape(u)}")
print(f"\ndimension uT: {np.shape(uT)}")
print("\ntranspuesta u: \n",uT)
prodcu2= uT*v
print(f"\nproducto elemento a elemento de uTv:\n {prodcu2}\n")



dimension u: (1, 4)

dimension uT: (4, 1)

transpuesta u: 
 [[0]
 [9]
 [1]
 [8]]

producto elemento a elemento de uTv:
 [[ 0  0  0  0]
 [81 72 54 18]
 [ 9  8  6  2]
 [72 64 48 16]]



In [ ]:
#? prodcu3= AB
try:
    prodcu3= A*B
    print(f"\nproducto elemento a elemento de AB:\n {prodcu3}\n")
except ValueError :
    prodcu3="Dimensiones incompatibles"
print(prodcu33)


Dimensiones incompatibles
